CREATE TABLE "S_PRODUCTS"  (	

"PRODUCT_ID" NUMBER NOT NULL ENABLE, 

 	"PRODUCT_CODE" VARCHAR2(50), 	

"PRODUCT_NAME" VARCHAR2(200), 	

"PRODUCT_UNIT" NUMBER, 	

"PRODUCT_CATEGORY" NUMBER, 

	"SELL_PRICE" NUMBER, 	

"BUY_PRICE" NUMBER, 

	"QUANTITY" NUMBER, 	

"R_ORDER_QUANTITY" NUMBER, 	

"PRODUCT_REMARKS" VARCHAR2(500), 

	 CONSTRAINT "S_PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID") ENABLE, 

	 CONSTRAINT "S_PRODUCTS_UK1" UNIQUE ("PRODUCT_CODE") ENABLE  )

 / 

ALTER TABLE "S_PRODUCTS" ADD CONSTRAINT "S_PRODUCTS_FK1" FOREIGN KEY ("PRODUCT_UNIT") 	 REFERENCES "S_UNIT" ("UNIT_ID") ON DELETE SET NULL ENABLE 

/ 

ALTER TABLE "S_PRODUCTS" ADD CONSTRAINT "S_PRODUCTS_FK2" FOREIGN KEY ("PRODUCT_CATEGORY") 	 REFERENCES "S_CATEGORY" ("CATEGORY_ID") ON DELETE SET NULL ENABLE

 / 

CREATE OR REPLACE TRIGGER "BI_S_PRODUCTS" 

 before insert on "S_PRODUCTS"        

 for each row begin   if :NEW."PRODUCT_ID" is null then  

 select "S_PRODUCTS_SEQ".nextval into :NEW."PRODUCT_ID" from sys.dual;

  end if;

 end;

 / 

ALTER TRIGGER "BI_S_PRODUCTS" ENABLE

 / 