CREATE TABLE "S_SELL_ORDER"  (	

"SELL_ORDER_ID" NUMBER NOT NULL ENABLE,

"SELL_ORDER_CLIENT_ID" NUMBER, 	

"SELL_ORDER_DATE" DATE, 	

"SELL_ORDER_TOTAL" NUMBER, 	 

CONSTRAINT "S_SELL_ORDER_PK" PRIMARY KEY ("SELL_ORDER_ID") ENABLE 

 ) 

/

 ALTER TABLE "S_SELL_ORDER" ADD CONSTRAINT "S_SELL_ORDER_FK" 

FOREIGN KEY ("SELL_ORDER_CLIENT_ID") 	 

REFERENCES "S_CLIENT" ("CLIENT_ID") ON DELETE SET NULL ENABLE 

/ 

CREATE OR REPLACE TRIGGER "BI_S_SELL_ORDER"  

before insert on "S_SELL_ORDER"         

for each row 

begin   

if :NEW."SELL_ORDER_ID" is null then   

select "S_SELL_ORDER_SEQ".nextval into :NEW."SELL_ORDER_ID" from sys.dual;

  end if; 

end; 

 / ALTER TRIGGER "BI_S_SELL_ORDER" ENABLE / 

-------

CREATE TABLE "S_SELL_ORDER_ITEMS"  (	

"SELL_ORDER_ITEM_ID" NUMBER NOT NULL ENABLE, 	

"SELL_ORDER_ID" NUMBER, 	

"PRODUCT_ID" NUMBER, 	

"PRODUCT_PRICE" NUMBER, 	

"PRODUCT_QUANTITY" NUMBER, 	

"PRODUCT_TOTAL" NUMBER, 	 

CONSTRAINT "S_SELL_ORDER_ITEMS_PK" PRIMARY KEY ("SELL_ORDER_ITEM_ID") ENABLE 

 )

 /

 ALTER TABLE "S_SELL_ORDER_ITEMS" ADD CONSTRAINT "S_SELL_ORDER_ITEMS_FK1" FOREIGN KEY ("SELL_ORDER_ID") 	 REFERENCES "S_SELL_ORDER" ("SELL_ORDER_ID") ON DELETE SET NULL ENABLE 

/ 

ALTER TABLE "S_SELL_ORDER_ITEMS" ADD CONSTRAINT "S_SELL_ORDER_ITEMS_FK2" FOREIGN KEY ("PRODUCT_ID") 	 REFERENCES "S_PRODUCTS" ("PRODUCT_ID") ON DELETE SET NULL ENABLE 

/ 

CREATE OR REPLACE TRIGGER 

"BI_S_SELL_ORDER_ITEMS"  

before insert on "S_SELL_ORDER_ITEMS"         

for each row 

begin   

if :NEW."SELL_ORDER_ITEM_ID" is null then  

 select "S_SELL_ORDER_ITEMS_SEQ".nextval into :NEW."SELL_ORDER_ITEM_ID" from sys.dual;

  end if; 

 end; 

 /

 ALTER TRIGGER "BI_S_SELL_ORDER_ITEMS" ENABLE

 / 